name: Publish Blog on Merge

on:
  push:
    branches:
      - main
    paths-ignore:
      - "blog/**"
      - "docs/**"
      - "README.md"
      - "CONTRIBUTING.md"
      - "CODE_OF_CONDUCT.md"
  workflow_dispatch:


concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Fetch-and-build-blog:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and Build blog content
        uses: ./.github/actions/docusaurus
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZATSIT_BLOG }}'
          channelId: live
          projectId: zatsit-blog
